# PDF Border Scale Configuration

# Border appearance
border:
  style: "rounded"        # Options: solid, rounded, dashed, dotted
  width: 1               # Border line width in points
  color: "0,0,0"        # RGB color (0-255 each)
  corner_radius: 5      # Corner radius in points (for rounded style)

# Spacing
spacing:
  outer_margin: 0.5      # Space from page edge to border
  inner_padding: 0.25    # Space from border to content
  unit: "inch"          # Options: inch, mm, pt

# Quality settings
quality:
  mode: "original"       # Options: original, high, medium, standard
  dpi: 300              # DPI for high/medium quality modes
  preserve_ratio: true   # Preserve aspect ratio

# Processing
processing:
  pages: "all"          # Page range: all, or specific like "1-5,10,15-20"
  confirm: true         # Show confirmation prompt (false to skip)